version: "3"
services:
  mongodb:
    image: mongo
    ports:
    - "8888:27017"
  app:
    build:
      context: "./app"
    volumes: 
      - /app/node_modules
      - ./app:/app
    ports:
      - "3000:3000"